# Generated by Django 4.1.3 on 2023-01-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userregistrationmodel',
            table='UserRegistration',
        ),
    ]
