# Generated by Django 4.1.3 on 2023-01-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userregistrationmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userregistrationmodel',
            table='UserRegistrations',
        ),
    ]
